### ISSUE TITLE
Werewolf needs a way to add an additional Archetype from the Celestial Attunement Metit

### ISSUE THREAD

**Issue by ptbrown121** [gnu-lorien/yorick#152]
The Celestial Attunement merit in Werewolf allows a character to have 2 archetypes.  Right now there is no way to add a second archetype to the character sheet.

My current work around is after character creation go to Merits and click on Celestial Attunement.  Then add your additional Archetype under specialization.  Finally, delete the original copy of Celestial Attunement from Merits.

I believe it would be better if at character creation you could add the specialization to Celestial Attunement directly or make it possible to add an additional Archetype after character creation.

**Comment by gnu-lorien** [comment]
Excellent. It looks like there are two major things in here that need to be done to support:

- Pick specializations as part of character creation pick. This would probably be nice all over the place.
- Support a second archetype.

Because of the way it's currently implemented, it's probably easier to add a second archetype to the class. Here's a rough checklist that comes to mind:

- Add archetype_2 to the tracked texts in cloud/main.js
- Add archetype_2 to the texts list in the Werewolf class
- Add archetype_2 to the print header for Werewolves

I think adding and testing that may be a good, easy task if you want to take it on as a smoke test for a development environment.

**Comment by ptbrown121** [comment]
Sure it shouldn't be to hard.
