### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by wirelesshnic** [gnu-lorien/yorick#2]
Some entries need custom fields.  I.e  the abilities section.  There is no place for me to put in my haven scouting.

**Comment by gnu-lorien** [comment]
Initially I thought this was already done, or shouldn't be done. Many of the other categories have a "Custom" field which accepts a specialization and there's no reason *not* to do that since limiting the fields values is a form of rules enforcement.

**Comment by gnu-lorien** [comment]
This turns out to be trickier because the update_trait call doesn't currently correctly handle a trait being renamed to collide with an existing trait. It also breaks the original assumption I had in using Arrays rather than relations: That the skill list was fixed and wouldn't ever become too large to load.

This assumption may already be wrong because of the way specializations are handled, but nobody's broken that limit before in the context of BNS. I suspect adding entirely custom fields would allow people to make characters from other systems which would definitely go over the 50 suggested max at the high end. As in, OWbN characters regularly have far more abilities than the smart limit for using Arrays on Parse.
