### ISSUE TITLE
Multiple fields with the same entry

### ISSUE THREAD

**Issue by wirelesshnic** [gnu-lorien/yorick#4]
I cannot take prey exclusion 3 times.  I want to put children, the elderly, and the handicapped.

**Comment by gnu-lorien** [comment]
Falls into the same category as issues #2. By base, the rules don't allow you to do things like this. It could be solved anyway with a custom field being allowed for any of them. See Lore Specializations for an example. More fields just need this extra option.

**Comment by wastevens** [comment]
There's several Backgrounds that, implicitly or explicitly, do allow you to take them multiple times, which is not presently supported.

At a minimum, I noticed Haven, Retainers and Alternate Identity.  (Haven and Retainers being complicated, of course, by also having specializations)

**Comment by gnu-lorien** [comment]
Good point. The name of something in the system I have *must* be unique within a category for the history to work correctly. Right now things that are always repeated use the "requires_specialization" requirement to have the name altered with additions. I suppose, generally, anything can be specialized since I only care about the preamble name and category for XP. This may be simple enough to add to the interface now as a button in the picking view where *anything* can be specialized when you click on it.

I think the choice would need to be in a few places:
1] When initially buying the ability that screen needs to have a check box or extra button to specify a specialization.
2] In each of the category views there should be an extra button that says something like, "Purchase additional as specialization" or some such to capture things like Haven where you usually aren't doing a bunch of them.
3] On the edit ability screen it should probably have a button that's "Specialize this" to create a specialization. It'll be hard to properly differentiate this from "notes" that @wirelesshnic requested until I get a display options thing in to filter those decisions.

**Comment by gnu-lorien** [comment]
1 and 3 have been implemented. The user base generally gets this now. Could still be better documentation, but the feature itself works.
