### ISSUE TITLE
Character Sheet Font Size

### ISSUE THREAD

**Issue by krylyyk** [gnu-lorien/yorick#91]
When the character sheet is actually printed, the font size looks like it's maybe 10 or 11. Is it possible to make the font size larger so it is easier to read in the dark settings of a LARP atmosphere?

**Comment by gnu-lorien** [comment]
I use Firefox and it gives me an option when printing to scale the page up when printing. It looks like Google Chrome has the same option. Do those work for you?

I laid the initial template out the way I did so that it would fit the biggest sheet possible on one page. I made sure to set up the CSS correctly so that the browser could scale properly based on user preference.

If people want to submit other printing template pages I can try to incorporate them. That's vaguely on my roadmap somewhere near the back because it's something I'd rather get submissions for than do myself.

**Comment by gnu-lorien** [comment]
This is in.
